-- +goose Up

-- Telemetry / identity columns on devices. last_seen_at already exists (00001).
ALTER TABLE devices
    ADD COLUMN IF NOT EXISTS reported_version  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS agent_version     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS machine_id        TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS last_telemetry_at TIMESTAMPTZ;

-- Lets the agent find "its" device on re-pair without colliding with manual rows.
CREATE UNIQUE INDEX IF NOT EXISTS idx_devices_machine_id
    ON devices(machine_id) WHERE machine_id <> '';

-- Pending pairing codes generated by a device awaiting an administrator claim.
CREATE TABLE IF NOT EXISTS device_enrollments (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code               TEXT NOT NULL UNIQUE CHECK (length(trim(code)) > 0),
    fleet_id           UUID NOT NULL REFERENCES fleets(id) ON DELETE CASCADE,
    machine_id         TEXT NOT NULL DEFAULT '',
    reported_hostname  TEXT NOT NULL DEFAULT '',
    reported_serial    TEXT NOT NULL DEFAULT '',
    reported_version   TEXT NOT NULL DEFAULT '',
    status             TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'claimed', 'expired')),
    device_id          UUID REFERENCES devices(id) ON DELETE SET NULL,
    claimed_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at         TIMESTAMPTZ NOT NULL,
    claimed_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_device_enrollments_status ON device_enrollments(status);
CREATE INDEX IF NOT EXISTS idx_device_enrollments_fleet ON device_enrollments(fleet_id);

-- A device keeps a single stable pending code per (fleet, machine) until claimed.
CREATE UNIQUE INDEX IF NOT EXISTS idx_device_enrollments_pending_machine
    ON device_enrollments(fleet_id, machine_id)
    WHERE status = 'pending' AND machine_id <> '';

-- Device authentication tokens (mirrors user_api_keys).
CREATE TABLE IF NOT EXISTS device_tokens (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id    UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    token_hash   BYTEA NOT NULL UNIQUE,
    token_prefix TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_device_tokens_device ON device_tokens(device_id);

-- Telemetry history for the per-device status page.
CREATE TABLE IF NOT EXISTS device_telemetry (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id        UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    payload          JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(payload) = 'object'),
    reported_version TEXT NOT NULL DEFAULT '',
    update_state     TEXT NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_device_telemetry_device_created
    ON device_telemetry(device_id, created_at DESC);

-- Queued remote commands for a device (force update / reboot). Groundwork: the
-- dispatch endpoints and table exist now; web buttons and agent execution land later.
CREATE TABLE IF NOT EXISTS device_commands (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id          UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    kind               TEXT NOT NULL CHECK (kind IN ('update', 'reboot')),
    status             TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'acknowledged', 'succeeded', 'failed')),
    target_version     TEXT NOT NULL DEFAULT '',
    result             TEXT NOT NULL DEFAULT '',
    created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    dispatched_at      TIMESTAMPTZ,
    completed_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_device_commands_device_status ON device_commands(device_id, status);

-- +goose Down

DROP INDEX IF EXISTS idx_device_commands_device_status;
DROP TABLE IF EXISTS device_commands;

DROP INDEX IF EXISTS idx_device_telemetry_device_created;
DROP TABLE IF EXISTS device_telemetry;

DROP INDEX IF EXISTS idx_device_tokens_device;
DROP TABLE IF EXISTS device_tokens;

DROP INDEX IF EXISTS idx_device_enrollments_pending_machine;
DROP INDEX IF EXISTS idx_device_enrollments_fleet;
DROP INDEX IF EXISTS idx_device_enrollments_status;
DROP TABLE IF EXISTS device_enrollments;

DROP INDEX IF EXISTS idx_devices_machine_id;

ALTER TABLE devices
    DROP COLUMN IF EXISTS last_telemetry_at,
    DROP COLUMN IF EXISTS machine_id,
    DROP COLUMN IF EXISTS agent_version,
    DROP COLUMN IF EXISTS reported_version;
